spring:  
  batch:
   job:
    enabled: true
   initializer:
    enabled: false
  jpa:
    show-sql:          true
    generate-ddl:      false
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      use-new-id-generator-mappings: SEQUENCE
      naming:
         implicit-strategy: jpa
         
batch-properties:
 system-prop-path: ./SysTest.properties
 
batch-evoice:
 url : jdbc:oracle:thin:@localhost:1522:ORCL
 username : SYSTEM 
 password : Grandsys1
 driverClassName : oracle.jdbc.driver.OracleDriver