package com.fubon.robot.batch.robot.evdata;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TBusCustomer generated by MyEclipse Persistence Tools
 */

@Entity
@Table(name="t_bus_customer")
public class TBusCustomer implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -397141615908661727L;
	
	@Id
	@Column(name = "CUSTOMER_ID")
	private String customerId;
	@Column(name = "CUSTOMER_NAME")
	private String customerName;
	@Column(name = "CUSTOMER_STATUS")
	private String customerStatus; // 未分配名單:10,待聯系:210,聯系中:211,已回收:213,已送件:214,已結案:215,未結案:216
	@Column(name = "CUSTOMER_TYPE")
	private String customerType;
	@Column(name = "ACTIVITY_ID")
	private String activityId;
	@Column(name = "INPUT_BATCH")
	private String inputBatch;
	@Column(name = "CURR_MONTH")
	private Integer currMonth;
	@Column(name = "ISSUE_TIME")
	private String issueTime;
	@Column(name = "INPUT_TIME")
	private String inputTime;
	@Column(name = "LAST_CONN_PATH")
	private String lastConnPath;
	@Column(name = "RECEIVE_USER_ID")
	private String receiveUserId; // 被分派使用者ID
	@Column(name = "RECEIVE_USER_NAME")
	private String receiveUserName; // 被分派使用者名稱
	@Column(name = "IS_RECYCLE")
	private String isRecycle;
	@Column(name = "CALL_HISTORY_ID")
	private String callHistoryId;
	@Column(name = "CALLING_TIME")
	private String callingTime;
	@Column(name = "RESULT_ID")
	private String resultId;
	@Column(name = "DISTRIBUTE_TIME")
	private String distributeTime;
	@Column(name = "SUBSCRIPTION_TIME")
	private String subscriptionTime;
	@Column(name = "RECYCLE_TIME")
	private String recycleTime;
	@Column(name = "SUBSCRIPTION_NOTE")
	private String subscriptionNote;
	@Column(name="IS_BLACKLIST")
	private String isBlackList;
	@Column(name="IS_SUBSCRIPTION")
	private String isSubscription;
	private String customer_01;
	private String customer_50;
	private String customer_49;
	private String customer_48;
	private String customer_47;
	private String customer_46;
	private String customer_45;
	private String customer_44;
	private String customer_43;
	private String customer_42;
	private String customer_41;
	private String customer_40;
	private String customer_39;
	private String customer_38;
	private String customer_37;
	private String customer_36;
	private String customer_35;
	private String customer_34;
	private String customer_33;
	private String customer_32;
	private String customer_31;
	private String customer_30;
	private String customer_29;
	private String customer_28; // 身份證ID(固定)
	private String customer_27;
	private String customer_26;
	private String customer_25;
	private String customer_24;
	private String customer_23;
	private String customer_22;
	private String customer_21;
	private String customer_20;
	private String customer_19;
	private String customer_18;
	private String customer_17;
	private String customer_16;
	private String customer_15;
	private String customer_14;
	private String customer_13;
	private String customer_12;
	private String customer_11;
	private String customer_10;
	private String customer_09;
	private String customer_08;
	private String customer_07;
	private String customer_06;
	private String customer_05;
	private String customer_04;
	private String customer_03;
	private String customer_02;
						   
	private String customer_51;
	private String customer_52;
	private String customer_53; // 區域別(固定)
	private String customer_54;
	private String customer_55; // 郵遞區號(固定)
	private String customer_56; // 地址(固定)
	private String customer_57; // 電子信箱(固定)
	private String customer_58; // 傳真號碼(固定)
	private String customer_59; // 商品名稱(固定)
	private String customer_60; // 產品代號(固定)
	private String customer_61;
	private String customer_62;
	private String customer_63;
	private String customer_64;
	private String customer_65;
	private String customer_66;
	private String customer_67;
	private String customer_68;
	private String customer_69;
	private String customer_70;
	private String customer_71;
	private String customer_72;
	private String customer_73;
	private String customer_74;
	private String customer_75;
	private String customer_76;
	private String customer_77;
	private String customer_78;
	private String customer_79;
	private String customer_80;
	private String customer_81;
	private String customer_82;
	private String customer_83;
	private String customer_84;
	private String customer_85;
	private String customer_86;
	private String customer_87;
	private String customer_88;
	private String customer_89;
	private String customer_90;
	private String customer_91;
	private String customer_92;
	private String customer_93;
	private String customer_94;
	private String customer_95;
	private String customer_96;
	private String customer_97;
	private String customer_98;
						   
	private String customer_99;
	private String customer_100;
	private String customer_101;
	private String customer_102;
	private String customer_103;
	private String customer_104;
	private String customer_105;
	private String customer_106;
	private String customer_107;
	private String customer_108;
	private String customer_109;
	private String customer_110;
	private String customer_111;
	private String customer_112;
	private String customer_113;
	private String customer_114;
	private String customer_115;
	private String customer_116;
	private String customer_117;
	private String customer_118;
	private String customer_119;
	private String customer_120;
	private String customer_121;
	private String customer_122;
	private String customer_123;
	private String customer_124;
	private String customer_125;
	private String customer_126;
	private String customer_127;
	private String customer_128;
	private String customer_129;
	private String customer_130;
	private String customer_131;
	private String customer_132;
	private String customer_133;
	private String customer_134;
	private String customer_135;
	private String customer_136;
	private String customer_137;
	private String customer_138;
	private String customer_139;
	private String customer_140;
	private String customer_141;
	private String customer_142;
	private String customer_143;
	private String customer_144;
	private String customer_145;
	private String customer_146;
	private String customer_147;
	private String customer_148;// 電話號碼(固定)
	private String customer_149;
	private String customer_150;
	private String customer_151;
	private String customer_152;
	private String customer_153;
	private String customer_154;
	private String customer_155;
	private String customer_156;
	private String customer_157;
	private String customer_158;
	private String customer_159;
	private String customer_160;
	private String customer_161;
	private String customer_162;
	private String customer_163;
	private String customer_164;
	private String customer_165;
	private String customer_166;
	private String customer_167;
	private String customer_168;
	private String customer_169;
	private String customer_170;
	private String customer_171;
	private String customer_172;
	private String customer_173;
	private String customer_174;
	private String customer_175;
	private String customer_176;
	private String customer_177;
	private String customer_178;
	private String customer_179;
	private String customer_180;
	private String customer_181;
	private String customer_182;
	private String customer_183;
	private String customer_184;
	private String customer_185;
	private String customer_186;
	private String customer_187;
	private String customer_188;
	private String customer_189;
	private String customer_190;
	private String customer_191;
	private String customer_192;
	private String customer_193;
	private String customer_194;
	private String customer_195;
	private String customer_196;
	private String customer_197;
	private String customer_198;
	private String customer_199;
	private String customer_200;
	private String customer_201;
	private String customer_202;
	private String customer_203;
	private String customer_204;
	private String customer_205;
	private String customer_206;
	private String customer_207;
	private String customer_208;
	private String customer_209;
	private String customer_210;
	private String customer_211;
	private String customer_212;
	private String customer_213;
	private String customer_214;
	private String customer_215;
	private String customer_216;
	private String customer_217;
	private String customer_218;
	private String customer_219;
	private String customer_220;
	private String customer_221;
	private String customer_222;
	private String customer_223;
	private String customer_224;
	private String customer_225;
	private String customer_226;
	private String customer_227;
	private String customer_228;
	private String customer_229;
	private String customer_230;
	private String customer_231;
	private String customer_232;
	private String customer_233;
	private String customer_234;
	private String customer_235;
	private String customer_236;
	private String customer_237;
	private String customer_238;
	private String customer_239;
	private String customer_240;
	private String customer_241;
	private String customer_242;
	private String customer_243;
	private String customer_244;
	private String customer_245;
	private String customer_246;
	private String customer_247;
	private String customer_248;
	private String customer_249;
	private String customer_250;
	@Column(name="MODIFY_TIME")
	private String modifyTime;
	@Column(name="PROPOSER_ID")
	private String proposerId;
	@Column(name="APPLY_TIME")
	private String applyTime;
	@Column(name="IS_TSR")
	private String isTsr;
	@Column(name="HIGHER_UP_ID")
	private String higherUpId;
	@Column(name="HANDLER_ID")
	private String handlerId;
	@Column(name="PROCESSING_TIME")
	private String processingTime;
	@Column(name="AUDITING_PASS_TIME")
	private String auditingPassTime;
	@Column(name="BLACK_STATUS")
	private String blackStatus;
	@Column(name="APPLY_REASON")
	private String applyReason;
	
	@Column(name="APPLY_REASON_DESC")
	private String applyReasonDesc;
	@Column(name="BLACKLIST_ID")
	private String blacklistId;
	@Column(name="proposer_name")
	private String proposerName;
	@Column(name="handler_name")
	private String handlerName;
	
	@Column(name="receive_user_code")
	private String receiveUserCode;// Add by Terry 2017-01-10

	private String callbackstatus; // 通話後狀態
	private String callbackresult;
	@Column(name="connect_Count")
	private int connectCount; //聯繫次數
	@Column(name="VISIT_MARK")
	private String visitMark; //訪問標識
	@Column(name="eff_Date")
	private String effDate;   //名單到期日

	@Column(name="SERVICE_ITEMS")
	private String serviceItems;// 服務項目
	@Column(name="UPDATE_DATE")
	private String updateDate;// 更新日期
	@Column(name="PRINT_MASK")
	private String printMask; // 列印標記
	@Column(name="TASK_JOB_NAME")
	private String taskJobName; // 如果是由自動匯入產生的,則會有一個TaskName記錄, 方便以後自動分派使用

	//private String listowner; // 名單所屬
	@Column(name="ASSIGNED_PROGRESS")
	private String assignedProgress; //自動分派進度 Add by Terry 2016-12-08

//	public String getActivityName() {
//		return activityName;
//	}
//
//	public void setActivityName(String activityName) {
//		this.activityName = activityName;
//	}

	public String getEffDate() {
		return effDate;
	}

	public void setEffDate(String effDate) {
		this.effDate = effDate;
	}

	public String getVisitMark() {
		return visitMark;
	}

	public void setVisitMark(String visitMark) {
		this.visitMark = visitMark;
	}

	public String getProposerName() {
		return proposerName;
	}

	public void setProposerName(String proposerName) {
		this.proposerName = proposerName;
	}

	public String getHandlerName() {
		return handlerName;
	}

	public void setHandlerName(String handlerName) {
		this.handlerName = handlerName;
	}
	

	public String getBlacklistId() {
		return blacklistId;
	}

	public void setBlacklistId(String blacklistId) {
		this.blacklistId = blacklistId;
	}

	public String getInputBatch() {
		return inputBatch;
	}

	public void setInputBatch(String inputBatch) {
		this.inputBatch = inputBatch;
	}

	public String getCustomerType() {
		return customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	public String getActivityId() {
		return activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public String getCustomerStatus() {
		return customerStatus;
	}

	public void setCustomerStatus(String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/** default constructor */
	public TBusCustomer() {
	}

	// Property accessors

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	

	public Integer getCurrMonth() {
		return currMonth;
	}

	public void setCurrMonth(Integer currMonth) {
		this.currMonth = currMonth;
	}

	public String getIssueTime() {
		return issueTime;
	}

	public void setIssueTime(String issueTime) {
		this.issueTime = issueTime;
	}

	public String getInputTime() {
		return inputTime;
	}

	public void setInputTime(String inputTime) {
		this.inputTime = inputTime;
	}

	public String getLastConnPath() {
		return lastConnPath;
	}

	public void setLastConnPath(String lastConnPath) {
		this.lastConnPath = lastConnPath;
	}

	public String getReceiveUserId() {
		return receiveUserId;
	}

	public void setReceiveUserId(String receiveUserId) {
		this.receiveUserId = receiveUserId;
	}

	public String getReceiveUserName() {
		return receiveUserName;
	}

	public void setReceiveUserName(String receiveUserName) {
		this.receiveUserName = receiveUserName;
	}

	public String getIsRecycle() {
		return isRecycle;
	}

	public void setIsRecycle(String isRecycle) {
		this.isRecycle = isRecycle;
	}

	public String getCallHistoryId() {
		return callHistoryId;
	}

	public void setCallHistoryId(String callHistoryId) {
		this.callHistoryId = callHistoryId;
	}

	public String getCallingTime() {
		return callingTime;
	}

	public void setCallingTime(String callingTime) {
		this.callingTime = callingTime;
	}

	public String getResultId() {
		return resultId;
	}

	public void setResultId(String resultId) {
		this.resultId = resultId;
	}

	public String getDistributeTime() {
		return distributeTime;
	}

	public void setDistributeTime(String distributeTime) {
		this.distributeTime = distributeTime;
	}

	public String getSubscriptionTime() {
		return subscriptionTime;
	}

	public void setSubscriptionTime(String subscriptionTime) {
		this.subscriptionTime = subscriptionTime;
	}

	public String getSubscriptionNote() {
		return subscriptionNote;
	}

	public void setSubscriptionNote(String subscriptionNote) {
		this.subscriptionNote = subscriptionNote;
	}

	public String getIsBlackList() {
		return isBlackList;
	}

	public void setIsBlackList(String isBlackList) {
		this.isBlackList = isBlackList;
	}

	public String getIsSubscription() {
		return isSubscription;
	}

	public void setIsSubscription(String isSubscription) {
		this.isSubscription = isSubscription;
	}

	public String getRecycleTime() {
		return recycleTime;
	}

	public void setRecycleTime(String recycleTime) {
		this.recycleTime = recycleTime;
	}

	public String getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getProposerId() {
		return proposerId;
	}

	public void setProposerId(String proposerId) {
		this.proposerId = proposerId;
	}

	public String getApplyTime() {
		return applyTime;
	}

	public void setApplyTime(String applyTime) {
		this.applyTime = applyTime;
	}


	public String getIsTsr() {
		return isTsr;
	}

	public void setIsTsr(String isTsr) {
		this.isTsr = isTsr;
	}

	public String getHigherUpId() {
		return higherUpId;
	}

	public void setHigherUpId(String higherUpId) {
		this.higherUpId = higherUpId;
	}

	public String getHandlerId() {
		return handlerId;
	}

	public void setHandlerId(String handlerId) {
		this.handlerId = handlerId;
	}

	public String getProcessingTime() {
		return processingTime;
	}

	public void setProcessingTime(String processingTime) {
		this.processingTime = processingTime;
	}

	public String getAuditingPassTime() {
		return auditingPassTime;
	}

	public void setAuditingPassTime(String auditingPassTime) {
		this.auditingPassTime = auditingPassTime;
	}

	public String getBlackStatus() {
		return blackStatus;
	}

	public void setBlackStatus(String blackStatus) {
		this.blackStatus = blackStatus;
	}

	public String getApplyReason() {
		return applyReason;
	}

	public void setApplyReason(String applyReason) {
		this.applyReason = applyReason;
	}

	public String getApplyReasonDesc() {
		return applyReasonDesc;
	}

	public void setApplyReasonDesc(String applyReasonDesc) {
		this.applyReasonDesc = applyReasonDesc;
	}

	
	public String getCustomer_01() {
		return customer_01;
	}

	public void setCustomer_01(String customer_01) {
		this.customer_01 = customer_01;
	}

	public String getCustomer_50() {
		return customer_50;
	}

	public void setCustomer_50(String customer_50) {
		this.customer_50 = customer_50;
	}

	public String getCustomer_49() {
		return customer_49;
	}

	public void setCustomer_49(String customer_49) {
		this.customer_49 = customer_49;
	}

	public String getCustomer_48() {
		return customer_48;
	}

	public void setCustomer_48(String customer_48) {
		this.customer_48 = customer_48;
	}

	public String getCustomer_47() {
		return customer_47;
	}

	public void setCustomer_47(String customer_47) {
		this.customer_47 = customer_47;
	}

	public String getCustomer_46() {
		return customer_46;
	}

	public void setCustomer_46(String customer_46) {
		this.customer_46 = customer_46;
	}

	public String getCustomer_45() {
		return customer_45;
	}

	public void setCustomer_45(String customer_45) {
		this.customer_45 = customer_45;
	}

	public String getCustomer_44() {
		return customer_44;
	}

	public void setCustomer_44(String customer_44) {
		this.customer_44 = customer_44;
	}

	public String getCustomer_43() {
		return customer_43;
	}

	public void setCustomer_43(String customer_43) {
		this.customer_43 = customer_43;
	}

	public String getCustomer_42() {
		return customer_42;
	}

	public void setCustomer_42(String customer_42) {
		this.customer_42 = customer_42;
	}

	public String getCustomer_41() {
		return customer_41;
	}

	public void setCustomer_41(String customer_41) {
		this.customer_41 = customer_41;
	}

	public String getCustomer_40() {
		return customer_40;
	}

	public void setCustomer_40(String customer_40) {
		this.customer_40 = customer_40;
	}

	public String getCustomer_39() {
		return customer_39;
	}

	public void setCustomer_39(String customer_39) {
		this.customer_39 = customer_39;
	}

	public String getCustomer_38() {
		return customer_38;
	}

	public void setCustomer_38(String customer_38) {
		this.customer_38 = customer_38;
	}

	public String getCustomer_37() {
		return customer_37;
	}

	public void setCustomer_37(String customer_37) {
		this.customer_37 = customer_37;
	}

	public String getCustomer_36() {
		return customer_36;
	}

	public void setCustomer_36(String customer_36) {
		this.customer_36 = customer_36;
	}

	public String getCustomer_35() {
		return customer_35;
	}

	public void setCustomer_35(String customer_35) {
		this.customer_35 = customer_35;
	}

	public String getCustomer_34() {
		return customer_34;
	}

	public void setCustomer_34(String customer_34) {
		this.customer_34 = customer_34;
	}

	public String getCustomer_33() {
		return customer_33;
	}

	public void setCustomer_33(String customer_33) {
		this.customer_33 = customer_33;
	}

	public String getCustomer_32() {
		return customer_32;
	}

	public void setCustomer_32(String customer_32) {
		this.customer_32 = customer_32;
	}

	public String getCustomer_31() {
		return customer_31;
	}

	public void setCustomer_31(String customer_31) {
		this.customer_31 = customer_31;
	}

	public String getCustomer_30() {
		return customer_30;
	}

	public void setCustomer_30(String customer_30) {
		this.customer_30 = customer_30;
	}

	public String getCustomer_29() {
		return customer_29;
	}

	public void setCustomer_29(String customer_29) {
		this.customer_29 = customer_29;
	}

	public String getCustomer_28() {
		return customer_28;
	}

	public void setCustomer_28(String customer_28) {
		this.customer_28 = customer_28;
	}

	public String getCustomer_27() {
		return customer_27;
	}

	public void setCustomer_27(String customer_27) {
		this.customer_27 = customer_27;
	}

	public String getCustomer_26() {
		return customer_26;
	}

	public void setCustomer_26(String customer_26) {
		this.customer_26 = customer_26;
	}

	public String getCustomer_25() {
		return customer_25;
	}

	public void setCustomer_25(String customer_25) {
		this.customer_25 = customer_25;
	}

	public String getCustomer_24() {
		return customer_24;
	}

	public void setCustomer_24(String customer_24) {
		this.customer_24 = customer_24;
	}

	public String getCustomer_23() {
		return customer_23;
	}

	public void setCustomer_23(String customer_23) {
		this.customer_23 = customer_23;
	}

	public String getCustomer_22() {
		return customer_22;
	}

	public void setCustomer_22(String customer_22) {
		this.customer_22 = customer_22;
	}

	public String getCustomer_21() {
		return customer_21;
	}

	public void setCustomer_21(String customer_21) {
		this.customer_21 = customer_21;
	}

	public String getCustomer_20() {
		return customer_20;
	}

	public void setCustomer_20(String customer_20) {
		this.customer_20 = customer_20;
	}

	public String getCustomer_19() {
		return customer_19;
	}

	public void setCustomer_19(String customer_19) {
		this.customer_19 = customer_19;
	}

	public String getCustomer_18() {
		return customer_18;
	}

	public void setCustomer_18(String customer_18) {
		this.customer_18 = customer_18;
	}

	public String getCustomer_17() {
		return customer_17;
	}

	public void setCustomer_17(String customer_17) {
		this.customer_17 = customer_17;
	}

	public String getCustomer_16() {
		return customer_16;
	}

	public void setCustomer_16(String customer_16) {
		this.customer_16 = customer_16;
	}

	public String getCustomer_15() {
		return customer_15;
	}

	public void setCustomer_15(String customer_15) {
		this.customer_15 = customer_15;
	}

	public String getCustomer_14() {
		return customer_14;
	}

	public void setCustomer_14(String customer_14) {
		this.customer_14 = customer_14;
	}

	public String getCustomer_13() {
		return customer_13;
	}

	public void setCustomer_13(String customer_13) {
		this.customer_13 = customer_13;
	}

	public String getCustomer_12() {
		return customer_12;
	}

	public void setCustomer_12(String customer_12) {
		this.customer_12 = customer_12;
	}

	public String getCustomer_11() {
		return customer_11;
	}

	public void setCustomer_11(String customer_11) {
		this.customer_11 = customer_11;
	}

	public String getCustomer_10() {
		return customer_10;
	}

	public void setCustomer_10(String customer_10) {
		this.customer_10 = customer_10;
	}

	public String getCustomer_09() {
		return customer_09;
	}

	public void setCustomer_09(String customer_09) {
		this.customer_09 = customer_09;
	}

	public String getCustomer_08() {
		return customer_08;
	}

	public void setCustomer_08(String customer_08) {
		this.customer_08 = customer_08;
	}

	public String getCustomer_07() {
		return customer_07;
	}

	public void setCustomer_07(String customer_07) {
		this.customer_07 = customer_07;
	}

	public String getCustomer_06() {
		return customer_06;
	}

	public void setCustomer_06(String customer_06) {
		this.customer_06 = customer_06;
	}

	public String getCustomer_05() {
		return customer_05;
	}

	public void setCustomer_05(String customer_05) {
		this.customer_05 = customer_05;
	}

	public String getCustomer_04() {
		return customer_04;
	}

	public void setCustomer_04(String customer_04) {
		this.customer_04 = customer_04;
	}

	public String getCustomer_03() {
		return customer_03;
	}

	public void setCustomer_03(String customer_03) {
		this.customer_03 = customer_03;
	}

	public String getCustomer_02() {
		return customer_02;
	}

	public void setCustomer_02(String customer_02) {
		this.customer_02 = customer_02;
	}

	public String getCustomer_51() {
		return customer_51;
	}

	public void setCustomer_51(String customer_51) {
		this.customer_51 = customer_51;
	}

	public String getCustomer_52() {
		return customer_52;
	}

	public void setCustomer_52(String customer_52) {
		this.customer_52 = customer_52;
	}

	public String getCustomer_53() {
		return customer_53;
	}

	public void setCustomer_53(String customer_53) {
		this.customer_53 = customer_53;
	}

	public String getCustomer_54() {
		return customer_54;
	}

	public void setCustomer_54(String customer_54) {
		this.customer_54 = customer_54;
	}

	public String getCustomer_55() {
		return customer_55;
	}

	public void setCustomer_55(String customer_55) {
		this.customer_55 = customer_55;
	}

	public String getCustomer_56() {
		return customer_56;
	}

	public void setCustomer_56(String customer_56) {
		this.customer_56 = customer_56;
	}

	public String getCustomer_57() {
		return customer_57;
	}

	public void setCustomer_57(String customer_57) {
		this.customer_57 = customer_57;
	}

	public String getCustomer_58() {
		return customer_58;
	}

	public void setCustomer_58(String customer_58) {
		this.customer_58 = customer_58;
	}

	public String getCustomer_59() {
		return customer_59;
	}

	public void setCustomer_59(String customer_59) {
		this.customer_59 = customer_59;
	}

	public String getCustomer_60() {
		return customer_60;
	}

	public void setCustomer_60(String customer_60) {
		this.customer_60 = customer_60;
	}

	public String getCustomer_61() {
		return customer_61;
	}

	public void setCustomer_61(String customer_61) {
		this.customer_61 = customer_61;
	}

	public String getCustomer_62() {
		return customer_62;
	}

	public void setCustomer_62(String customer_62) {
		this.customer_62 = customer_62;
	}

	public String getCustomer_63() {
		return customer_63;
	}

	public void setCustomer_63(String customer_63) {
		this.customer_63 = customer_63;
	}

	public String getCustomer_64() {
		return customer_64;
	}

	public void setCustomer_64(String customer_64) {
		this.customer_64 = customer_64;
	}

	public String getCustomer_65() {
		return customer_65;
	}

	public void setCustomer_65(String customer_65) {
		this.customer_65 = customer_65;
	}

	public String getCustomer_66() {
		return customer_66;
	}

	public void setCustomer_66(String customer_66) {
		this.customer_66 = customer_66;
	}

	public String getCustomer_67() {
		return customer_67;
	}

	public void setCustomer_67(String customer_67) {
		this.customer_67 = customer_67;
	}

	public String getCustomer_68() {
		return customer_68;
	}

	public void setCustomer_68(String customer_68) {
		this.customer_68 = customer_68;
	}

	public String getCustomer_69() {
		return customer_69;
	}

	public void setCustomer_69(String customer_69) {
		this.customer_69 = customer_69;
	}

	public String getCustomer_70() {
		return customer_70;
	}

	public void setCustomer_70(String customer_70) {
		this.customer_70 = customer_70;
	}

	public String getCustomer_71() {
		return customer_71;
	}

	public void setCustomer_71(String customer_71) {
		this.customer_71 = customer_71;
	}

	public String getCustomer_72() {
		return customer_72;
	}

	public void setCustomer_72(String customer_72) {
		this.customer_72 = customer_72;
	}

	public String getCustomer_73() {
		return customer_73;
	}

	public void setCustomer_73(String customer_73) {
		this.customer_73 = customer_73;
	}

	public String getCustomer_74() {
		return customer_74;
	}

	public void setCustomer_74(String customer_74) {
		this.customer_74 = customer_74;
	}

	public String getCustomer_75() {
		return customer_75;
	}

	public void setCustomer_75(String customer_75) {
		this.customer_75 = customer_75;
	}

	public String getCustomer_76() {
		return customer_76;
	}

	public void setCustomer_76(String customer_76) {
		this.customer_76 = customer_76;
	}

	public String getCustomer_77() {
		return customer_77;
	}

	public void setCustomer_77(String customer_77) {
		this.customer_77 = customer_77;
	}

	public String getCustomer_78() {
		return customer_78;
	}

	public void setCustomer_78(String customer_78) {
		this.customer_78 = customer_78;
	}

	public String getCustomer_79() {
		return customer_79;
	}

	public void setCustomer_79(String customer_79) {
		this.customer_79 = customer_79;
	}

	public String getCustomer_80() {
		return customer_80;
	}

	public void setCustomer_80(String customer_80) {
		this.customer_80 = customer_80;
	}

	public String getCustomer_81() {
		return customer_81;
	}

	public void setCustomer_81(String customer_81) {
		this.customer_81 = customer_81;
	}

	public String getCustomer_82() {
		return customer_82;
	}

	public void setCustomer_82(String customer_82) {
		this.customer_82 = customer_82;
	}

	public String getCustomer_83() {
		return customer_83;
	}

	public void setCustomer_83(String customer_83) {
		this.customer_83 = customer_83;
	}

	public String getCustomer_84() {
		return customer_84;
	}

	public void setCustomer_84(String customer_84) {
		this.customer_84 = customer_84;
	}

	public String getCustomer_85() {
		return customer_85;
	}

	public void setCustomer_85(String customer_85) {
		this.customer_85 = customer_85;
	}

	public String getCustomer_86() {
		return customer_86;
	}

	public void setCustomer_86(String customer_86) {
		this.customer_86 = customer_86;
	}

	public String getCustomer_87() {
		return customer_87;
	}

	public void setCustomer_87(String customer_87) {
		this.customer_87 = customer_87;
	}

	public String getCustomer_88() {
		return customer_88;
	}

	public void setCustomer_88(String customer_88) {
		this.customer_88 = customer_88;
	}

	public String getCustomer_89() {
		return customer_89;
	}

	public void setCustomer_89(String customer_89) {
		this.customer_89 = customer_89;
	}

	public String getCustomer_90() {
		return customer_90;
	}

	public void setCustomer_90(String customer_90) {
		this.customer_90 = customer_90;
	}

	public String getCustomer_91() {
		return customer_91;
	}

	public void setCustomer_91(String customer_91) {
		this.customer_91 = customer_91;
	}

	public String getCustomer_92() {
		return customer_92;
	}

	public void setCustomer_92(String customer_92) {
		this.customer_92 = customer_92;
	}

	public String getCustomer_93() {
		return customer_93;
	}

	public void setCustomer_93(String customer_93) {
		this.customer_93 = customer_93;
	}

	public String getCustomer_94() {
		return customer_94;
	}

	public void setCustomer_94(String customer_94) {
		this.customer_94 = customer_94;
	}

	public String getCustomer_95() {
		return customer_95;
	}

	public void setCustomer_95(String customer_95) {
		this.customer_95 = customer_95;
	}

	public String getCustomer_96() {
		return customer_96;
	}

	public void setCustomer_96(String customer_96) {
		this.customer_96 = customer_96;
	}

	public String getCustomer_97() {
		return customer_97;
	}

	public void setCustomer_97(String customer_97) {
		this.customer_97 = customer_97;
	}

	public String getCustomer_98() {
		return customer_98;
	}

	public void setCustomer_98(String customer_98) {
		this.customer_98 = customer_98;
	}

	public String getCustomer_99() {
		return customer_99;
	}

	public void setCustomer_99(String customer_99) {
		this.customer_99 = customer_99;
	}

	public String getCustomer_100() {
		return customer_100;
	}

	public void setCustomer_100(String customer_100) {
		this.customer_100 = customer_100;
	}

	public String getCustomer_101() {
		return customer_101;
	}

	public void setCustomer_101(String customer_101) {
		this.customer_101 = customer_101;
	}

	public String getCustomer_102() {
		return customer_102;
	}

	public void setCustomer_102(String customer_102) {
		this.customer_102 = customer_102;
	}

	public String getCustomer_103() {
		return customer_103;
	}

	public void setCustomer_103(String customer_103) {
		this.customer_103 = customer_103;
	}

	public String getCustomer_104() {
		return customer_104;
	}

	public void setCustomer_104(String customer_104) {
		this.customer_104 = customer_104;
	}

	public String getCustomer_105() {
		return customer_105;
	}

	public void setCustomer_105(String customer_105) {
		this.customer_105 = customer_105;
	}

	public String getCustomer_106() {
		return customer_106;
	}

	public void setCustomer_106(String customer_106) {
		this.customer_106 = customer_106;
	}

	public String getCustomer_107() {
		return customer_107;
	}

	public void setCustomer_107(String customer_107) {
		this.customer_107 = customer_107;
	}

	public String getCustomer_108() {
		return customer_108;
	}

	public void setCustomer_108(String customer_108) {
		this.customer_108 = customer_108;
	}

	public String getCustomer_109() {
		return customer_109;
	}

	public void setCustomer_109(String customer_109) {
		this.customer_109 = customer_109;
	}

	public String getCustomer_110() {
		return customer_110;
	}

	public void setCustomer_110(String customer_110) {
		this.customer_110 = customer_110;
	}

	public String getCustomer_111() {
		return customer_111;
	}

	public void setCustomer_111(String customer_111) {
		this.customer_111 = customer_111;
	}

	public String getCustomer_112() {
		return customer_112;
	}

	public void setCustomer_112(String customer_112) {
		this.customer_112 = customer_112;
	}

	public String getCustomer_113() {
		return customer_113;
	}

	public void setCustomer_113(String customer_113) {
		this.customer_113 = customer_113;
	}

	public String getCustomer_114() {
		return customer_114;
	}

	public void setCustomer_114(String customer_114) {
		this.customer_114 = customer_114;
	}

	public String getCustomer_115() {
		return customer_115;
	}

	public void setCustomer_115(String customer_115) {
		this.customer_115 = customer_115;
	}

	public String getCustomer_116() {
		return customer_116;
	}

	public void setCustomer_116(String customer_116) {
		this.customer_116 = customer_116;
	}

	public String getCustomer_117() {
		return customer_117;
	}

	public void setCustomer_117(String customer_117) {
		this.customer_117 = customer_117;
	}

	public String getCustomer_118() {
		return customer_118;
	}

	public void setCustomer_118(String customer_118) {
		this.customer_118 = customer_118;
	}

	public String getCustomer_119() {
		return customer_119;
	}

	public void setCustomer_119(String customer_119) {
		this.customer_119 = customer_119;
	}

	public String getCustomer_120() {
		return customer_120;
	}

	public void setCustomer_120(String customer_120) {
		this.customer_120 = customer_120;
	}

	public String getCustomer_121() {
		return customer_121;
	}

	public void setCustomer_121(String customer_121) {
		this.customer_121 = customer_121;
	}

	public String getCustomer_122() {
		return customer_122;
	}

	public void setCustomer_122(String customer_122) {
		this.customer_122 = customer_122;
	}

	public String getCustomer_123() {
		return customer_123;
	}

	public void setCustomer_123(String customer_123) {
		this.customer_123 = customer_123;
	}

	public String getCustomer_124() {
		return customer_124;
	}

	public void setCustomer_124(String customer_124) {
		this.customer_124 = customer_124;
	}

	public String getCustomer_125() {
		return customer_125;
	}

	public void setCustomer_125(String customer_125) {
		this.customer_125 = customer_125;
	}

	public String getCustomer_126() {
		return customer_126;
	}

	public void setCustomer_126(String customer_126) {
		this.customer_126 = customer_126;
	}

	public String getCustomer_127() {
		return customer_127;
	}

	public void setCustomer_127(String customer_127) {
		this.customer_127 = customer_127;
	}

	public String getCustomer_128() {
		return customer_128;
	}

	public void setCustomer_128(String customer_128) {
		this.customer_128 = customer_128;
	}

	public String getCustomer_129() {
		return customer_129;
	}

	public void setCustomer_129(String customer_129) {
		this.customer_129 = customer_129;
	}

	public String getCustomer_130() {
		return customer_130;
	}

	public void setCustomer_130(String customer_130) {
		this.customer_130 = customer_130;
	}

	public String getCustomer_131() {
		return customer_131;
	}

	public void setCustomer_131(String customer_131) {
		this.customer_131 = customer_131;
	}

	public String getCustomer_132() {
		return customer_132;
	}

	public void setCustomer_132(String customer_132) {
		this.customer_132 = customer_132;
	}

	public String getCustomer_133() {
		return customer_133;
	}

	public void setCustomer_133(String customer_133) {
		this.customer_133 = customer_133;
	}

	public String getCustomer_134() {
		return customer_134;
	}

	public void setCustomer_134(String customer_134) {
		this.customer_134 = customer_134;
	}

	public String getCustomer_135() {
		return customer_135;
	}

	public void setCustomer_135(String customer_135) {
		this.customer_135 = customer_135;
	}

	public String getCustomer_136() {
		return customer_136;
	}

	public void setCustomer_136(String customer_136) {
		this.customer_136 = customer_136;
	}

	public String getCustomer_137() {
		return customer_137;
	}

	public void setCustomer_137(String customer_137) {
		this.customer_137 = customer_137;
	}

	public String getCustomer_138() {
		return customer_138;
	}

	public void setCustomer_138(String customer_138) {
		this.customer_138 = customer_138;
	}

	public String getCustomer_139() {
		return customer_139;
	}

	public void setCustomer_139(String customer_139) {
		this.customer_139 = customer_139;
	}

	public String getCustomer_140() {
		return customer_140;
	}

	public void setCustomer_140(String customer_140) {
		this.customer_140 = customer_140;
	}

	public String getCustomer_141() {
		return customer_141;
	}

	public void setCustomer_141(String customer_141) {
		this.customer_141 = customer_141;
	}

	public String getCustomer_142() {
		return customer_142;
	}

	public void setCustomer_142(String customer_142) {
		this.customer_142 = customer_142;
	}

	public String getCustomer_143() {
		return customer_143;
	}

	public void setCustomer_143(String customer_143) {
		this.customer_143 = customer_143;
	}

	public String getCustomer_144() {
		return customer_144;
	}

	public void setCustomer_144(String customer_144) {
		this.customer_144 = customer_144;
	}

	public String getCustomer_145() {
		return customer_145;
	}

	public void setCustomer_145(String customer_145) {
		this.customer_145 = customer_145;
	}

	public String getCustomer_146() {
		return customer_146;
	}

	public void setCustomer_146(String customer_146) {
		this.customer_146 = customer_146;
	}

	public String getCustomer_147() {
		return customer_147;
	}

	public void setCustomer_147(String customer_147) {
		this.customer_147 = customer_147;
	}

	public String getCustomer_148() {
		return customer_148;
	}

	public void setCustomer_148(String customer_148) {
		this.customer_148 = customer_148;
	}

	public String getCustomer_149() {
		return customer_149;
	}

	public void setCustomer_149(String customer_149) {
		this.customer_149 = customer_149;
	}

	public String getCustomer_150() {
		return customer_150;
	}

	public void setCustomer_150(String customer_150) {
		this.customer_150 = customer_150;
	}

	public String getCustomer_151() {
		return customer_151;
	}

	public void setCustomer_151(String customer_151) {
		this.customer_151 = customer_151;
	}

	public String getCustomer_152() {
		return customer_152;
	}

	public void setCustomer_152(String customer_152) {
		this.customer_152 = customer_152;
	}

	public String getCustomer_153() {
		return customer_153;
	}

	public void setCustomer_153(String customer_153) {
		this.customer_153 = customer_153;
	}

	public String getCustomer_154() {
		return customer_154;
	}

	public void setCustomer_154(String customer_154) {
		this.customer_154 = customer_154;
	}

	public String getCustomer_155() {
		return customer_155;
	}

	public void setCustomer_155(String customer_155) {
		this.customer_155 = customer_155;
	}

	public String getCustomer_156() {
		return customer_156;
	}

	public void setCustomer_156(String customer_156) {
		this.customer_156 = customer_156;
	}

	public String getCustomer_157() {
		return customer_157;
	}

	public void setCustomer_157(String customer_157) {
		this.customer_157 = customer_157;
	}

	public String getCustomer_158() {
		return customer_158;
	}

	public void setCustomer_158(String customer_158) {
		this.customer_158 = customer_158;
	}

	public String getCustomer_159() {
		return customer_159;
	}

	public void setCustomer_159(String customer_159) {
		this.customer_159 = customer_159;
	}

	public String getCustomer_160() {
		return customer_160;
	}

	public void setCustomer_160(String customer_160) {
		this.customer_160 = customer_160;
	}

	public String getCustomer_161() {
		return customer_161;
	}

	public void setCustomer_161(String customer_161) {
		this.customer_161 = customer_161;
	}

	public String getCustomer_162() {
		return customer_162;
	}

	public void setCustomer_162(String customer_162) {
		this.customer_162 = customer_162;
	}

	public String getCustomer_163() {
		return customer_163;
	}

	public void setCustomer_163(String customer_163) {
		this.customer_163 = customer_163;
	}

	public String getCustomer_164() {
		return customer_164;
	}

	public void setCustomer_164(String customer_164) {
		this.customer_164 = customer_164;
	}

	public String getCustomer_165() {
		return customer_165;
	}

	public void setCustomer_165(String customer_165) {
		this.customer_165 = customer_165;
	}

	public String getCustomer_166() {
		return customer_166;
	}

	public void setCustomer_166(String customer_166) {
		this.customer_166 = customer_166;
	}

	public String getCustomer_167() {
		return customer_167;
	}

	public void setCustomer_167(String customer_167) {
		this.customer_167 = customer_167;
	}

	public String getCustomer_168() {
		return customer_168;
	}

	public void setCustomer_168(String customer_168) {
		this.customer_168 = customer_168;
	}

	public String getCustomer_169() {
		return customer_169;
	}

	public void setCustomer_169(String customer_169) {
		this.customer_169 = customer_169;
	}

	public String getCustomer_170() {
		return customer_170;
	}

	public void setCustomer_170(String customer_170) {
		this.customer_170 = customer_170;
	}

	public String getCustomer_171() {
		return customer_171;
	}

	public void setCustomer_171(String customer_171) {
		this.customer_171 = customer_171;
	}

	public String getCustomer_172() {
		return customer_172;
	}

	public void setCustomer_172(String customer_172) {
		this.customer_172 = customer_172;
	}

	public String getCustomer_173() {
		return customer_173;
	}

	public void setCustomer_173(String customer_173) {
		this.customer_173 = customer_173;
	}

	public String getCustomer_174() {
		return customer_174;
	}

	public void setCustomer_174(String customer_174) {
		this.customer_174 = customer_174;
	}

	public String getCustomer_175() {
		return customer_175;
	}

	public void setCustomer_175(String customer_175) {
		this.customer_175 = customer_175;
	}

	public String getCustomer_176() {
		return customer_176;
	}

	public void setCustomer_176(String customer_176) {
		this.customer_176 = customer_176;
	}

	public String getCustomer_177() {
		return customer_177;
	}

	public void setCustomer_177(String customer_177) {
		this.customer_177 = customer_177;
	}

	public String getCustomer_178() {
		return customer_178;
	}

	public void setCustomer_178(String customer_178) {
		this.customer_178 = customer_178;
	}

	public String getCustomer_179() {
		return customer_179;
	}

	public void setCustomer_179(String customer_179) {
		this.customer_179 = customer_179;
	}

	public String getCustomer_180() {
		return customer_180;
	}

	public void setCustomer_180(String customer_180) {
		this.customer_180 = customer_180;
	}

	public String getCustomer_181() {
		return customer_181;
	}

	public void setCustomer_181(String customer_181) {
		this.customer_181 = customer_181;
	}

	public String getCustomer_182() {
		return customer_182;
	}

	public void setCustomer_182(String customer_182) {
		this.customer_182 = customer_182;
	}

	public String getCustomer_183() {
		return customer_183;
	}

	public void setCustomer_183(String customer_183) {
		this.customer_183 = customer_183;
	}

	public String getCustomer_184() {
		return customer_184;
	}

	public void setCustomer_184(String customer_184) {
		this.customer_184 = customer_184;
	}

	public String getCustomer_185() {
		return customer_185;
	}

	public void setCustomer_185(String customer_185) {
		this.customer_185 = customer_185;
	}

	public String getCustomer_186() {
		return customer_186;
	}

	public void setCustomer_186(String customer_186) {
		this.customer_186 = customer_186;
	}

	public String getCustomer_187() {
		return customer_187;
	}

	public void setCustomer_187(String customer_187) {
		this.customer_187 = customer_187;
	}

	public String getCustomer_188() {
		return customer_188;
	}

	public void setCustomer_188(String customer_188) {
		this.customer_188 = customer_188;
	}

	public String getCustomer_189() {
		return customer_189;
	}

	public void setCustomer_189(String customer_189) {
		this.customer_189 = customer_189;
	}

	public String getCustomer_190() {
		return customer_190;
	}

	public void setCustomer_190(String customer_190) {
		this.customer_190 = customer_190;
	}

	public String getCustomer_191() {
		return customer_191;
	}

	public void setCustomer_191(String customer_191) {
		this.customer_191 = customer_191;
	}

	public String getCustomer_192() {
		return customer_192;
	}

	public void setCustomer_192(String customer_192) {
		this.customer_192 = customer_192;
	}

	public String getCustomer_193() {
		return customer_193;
	}

	public void setCustomer_193(String customer_193) {
		this.customer_193 = customer_193;
	}

	public String getCustomer_194() {
		return customer_194;
	}

	public void setCustomer_194(String customer_194) {
		this.customer_194 = customer_194;
	}

	public String getCustomer_195() {
		return customer_195;
	}

	public void setCustomer_195(String customer_195) {
		this.customer_195 = customer_195;
	}

	public String getCustomer_196() {
		return customer_196;
	}

	public void setCustomer_196(String customer_196) {
		this.customer_196 = customer_196;
	}

	public String getCustomer_197() {
		return customer_197;
	}

	public void setCustomer_197(String customer_197) {
		this.customer_197 = customer_197;
	}

	public String getCustomer_198() {
		return customer_198;
	}

	public void setCustomer_198(String customer_198) {
		this.customer_198 = customer_198;
	}

	public String getCustomer_199() {
		return customer_199;
	}

	public void setCustomer_199(String customer_199) {
		this.customer_199 = customer_199;
	}

	public String getCustomer_200() {
		return customer_200;
	}

	public void setCustomer_200(String customer_200) {
		this.customer_200 = customer_200;
	}

	public String getCustomer_201() {
		return customer_201;
	}

	public void setCustomer_201(String customer_201) {
		this.customer_201 = customer_201;
	}

	public String getCustomer_202() {
		return customer_202;
	}

	public void setCustomer_202(String customer_202) {
		this.customer_202 = customer_202;
	}

	public String getCustomer_203() {
		return customer_203;
	}

	public void setCustomer_203(String customer_203) {
		this.customer_203 = customer_203;
	}

	public String getCustomer_204() {
		return customer_204;
	}

	public void setCustomer_204(String customer_204) {
		this.customer_204 = customer_204;
	}

	public String getCustomer_205() {
		return customer_205;
	}

	public void setCustomer_205(String customer_205) {
		this.customer_205 = customer_205;
	}

	public String getCustomer_206() {
		return customer_206;
	}

	public void setCustomer_206(String customer_206) {
		this.customer_206 = customer_206;
	}

	public String getCustomer_207() {
		return customer_207;
	}

	public void setCustomer_207(String customer_207) {
		this.customer_207 = customer_207;
	}

	public String getCustomer_208() {
		return customer_208;
	}

	public void setCustomer_208(String customer_208) {
		this.customer_208 = customer_208;
	}

	public String getCustomer_209() {
		return customer_209;
	}

	public void setCustomer_209(String customer_209) {
		this.customer_209 = customer_209;
	}

	public String getCustomer_210() {
		return customer_210;
	}

	public void setCustomer_210(String customer_210) {
		this.customer_210 = customer_210;
	}

	public String getCustomer_211() {
		return customer_211;
	}

	public void setCustomer_211(String customer_211) {
		this.customer_211 = customer_211;
	}

	public String getCustomer_212() {
		return customer_212;
	}

	public void setCustomer_212(String customer_212) {
		this.customer_212 = customer_212;
	}

	public String getCustomer_213() {
		return customer_213;
	}

	public void setCustomer_213(String customer_213) {
		this.customer_213 = customer_213;
	}

	public String getCustomer_214() {
		return customer_214;
	}

	public void setCustomer_214(String customer_214) {
		this.customer_214 = customer_214;
	}

	public String getCustomer_215() {
		return customer_215;
	}

	public void setCustomer_215(String customer_215) {
		this.customer_215 = customer_215;
	}

	public String getCustomer_216() {
		return customer_216;
	}

	public void setCustomer_216(String customer_216) {
		this.customer_216 = customer_216;
	}

	public String getCustomer_217() {
		return customer_217;
	}

	public void setCustomer_217(String customer_217) {
		this.customer_217 = customer_217;
	}

	public String getCustomer_218() {
		return customer_218;
	}

	public void setCustomer_218(String customer_218) {
		this.customer_218 = customer_218;
	}

	public String getCustomer_219() {
		return customer_219;
	}

	public void setCustomer_219(String customer_219) {
		this.customer_219 = customer_219;
	}

	public String getCustomer_220() {
		return customer_220;
	}

	public void setCustomer_220(String customer_220) {
		this.customer_220 = customer_220;
	}

	public String getCustomer_221() {
		return customer_221;
	}

	public void setCustomer_221(String customer_221) {
		this.customer_221 = customer_221;
	}

	public String getCustomer_222() {
		return customer_222;
	}

	public void setCustomer_222(String customer_222) {
		this.customer_222 = customer_222;
	}

	public String getCustomer_223() {
		return customer_223;
	}

	public void setCustomer_223(String customer_223) {
		this.customer_223 = customer_223;
	}

	public String getCustomer_224() {
		return customer_224;
	}

	public void setCustomer_224(String customer_224) {
		this.customer_224 = customer_224;
	}

	public String getCustomer_225() {
		return customer_225;
	}

	public void setCustomer_225(String customer_225) {
		this.customer_225 = customer_225;
	}

	public String getCustomer_226() {
		return customer_226;
	}

	public void setCustomer_226(String customer_226) {
		this.customer_226 = customer_226;
	}

	public String getCustomer_227() {
		return customer_227;
	}

	public void setCustomer_227(String customer_227) {
		this.customer_227 = customer_227;
	}

	public String getCustomer_228() {
		return customer_228;
	}

	public void setCustomer_228(String customer_228) {
		this.customer_228 = customer_228;
	}

	public String getCustomer_229() {
		return customer_229;
	}

	public void setCustomer_229(String customer_229) {
		this.customer_229 = customer_229;
	}

	public String getCustomer_230() {
		return customer_230;
	}

	public void setCustomer_230(String customer_230) {
		this.customer_230 = customer_230;
	}

	public String getCustomer_231() {
		return customer_231;
	}

	public void setCustomer_231(String customer_231) {
		this.customer_231 = customer_231;
	}

	public String getCustomer_232() {
		return customer_232;
	}

	public void setCustomer_232(String customer_232) {
		this.customer_232 = customer_232;
	}

	public String getCustomer_233() {
		return customer_233;
	}

	public void setCustomer_233(String customer_233) {
		this.customer_233 = customer_233;
	}

	public String getCustomer_234() {
		return customer_234;
	}

	public void setCustomer_234(String customer_234) {
		this.customer_234 = customer_234;
	}

	public String getCustomer_235() {
		return customer_235;
	}

	public void setCustomer_235(String customer_235) {
		this.customer_235 = customer_235;
	}

	public String getCustomer_236() {
		return customer_236;
	}

	public void setCustomer_236(String customer_236) {
		this.customer_236 = customer_236;
	}

	public String getCustomer_237() {
		return customer_237;
	}

	public void setCustomer_237(String customer_237) {
		this.customer_237 = customer_237;
	}

	public String getCustomer_238() {
		return customer_238;
	}

	public void setCustomer_238(String customer_238) {
		this.customer_238 = customer_238;
	}

	public String getCustomer_239() {
		return customer_239;
	}

	public void setCustomer_239(String customer_239) {
		this.customer_239 = customer_239;
	}

	public String getCustomer_240() {
		return customer_240;
	}

	public void setCustomer_240(String customer_240) {
		this.customer_240 = customer_240;
	}

	public String getCustomer_241() {
		return customer_241;
	}

	public void setCustomer_241(String customer_241) {
		this.customer_241 = customer_241;
	}

	public String getCustomer_242() {
		return customer_242;
	}

	public void setCustomer_242(String customer_242) {
		this.customer_242 = customer_242;
	}

	public String getCustomer_243() {
		return customer_243;
	}

	public void setCustomer_243(String customer_243) {
		this.customer_243 = customer_243;
	}

	public String getCustomer_244() {
		return customer_244;
	}

	public void setCustomer_244(String customer_244) {
		this.customer_244 = customer_244;
	}

	public String getCustomer_245() {
		return customer_245;
	}

	public void setCustomer_245(String customer_245) {
		this.customer_245 = customer_245;
	}

	public String getCustomer_246() {
		return customer_246;
	}

	public void setCustomer_246(String customer_246) {
		this.customer_246 = customer_246;
	}

	public String getCustomer_247() {
		return customer_247;
	}

	public void setCustomer_247(String customer_247) {
		this.customer_247 = customer_247;
	}

	public String getCustomer_248() {
		return customer_248;
	}

	public void setCustomer_248(String customer_248) {
		this.customer_248 = customer_248;
	}

	public String getCustomer_249() {
		return customer_249;
	}

	public void setCustomer_249(String customer_249) {
		this.customer_249 = customer_249;
	}

	public String getCustomer_250() {
		return customer_250;
	}

	public void setCustomer_250(String customer_250) {
		this.customer_250 = customer_250;
	}

	//add by terry 2016-01-10 start
	public String getReceiveUserCode() {
		return receiveUserCode;
	}

	public void setReceiveUserCode(String receiveUserCode) {
		this.receiveUserCode = receiveUserCode;
	}
	//add by terry 2016-01-10 end

	public String getCallbackstatus() {
		return callbackstatus;
	}

	public String getCallbackresult() {
		return callbackresult;
	}

	public void setCallbackresult(String callbackresult) {
		this.callbackresult = callbackresult;
	}

	public void setCallbackstatus(String callbackstatus) {
		this.callbackstatus = callbackstatus;
	}



	public int getConnectCount() {
		return connectCount;
	}

	public void setConnectCount(int connectCount) {
		this.connectCount = connectCount;
	}

//	public String getCallingTimeStart() {
//		return callingTimeStart;
//	}
//
//	public void setCallingTimeStart(String callingTimeStart) {
//		this.callingTimeStart = callingTimeStart;
//	}
//
//	public String getCallingTimeEnd() {
//		return callingTimeEnd;
//	}
//
//	public void setCallingTimeEnd(String callingTimeEnd) {
//		this.callingTimeEnd = callingTimeEnd;
//	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public String getServiceItems() {
		return serviceItems;
	}

	public void setServiceItems(String serviceItems) {
		this.serviceItems = serviceItems;
	}

	public String getPrintMask() {
		return printMask;
	}

	public void setPrintMask(String printMask) {
		this.printMask = printMask;
	}

	public String getTaskJobName() {
		return taskJobName;
	}

	public void setTaskJobName(String taskJobName) {
		this.taskJobName = taskJobName;
	}

//	public String getListowner() {
//		return listowner;
//	}
//
//	public void setListowner(String listowner) {
//		this.listowner = listowner;
//	}
	// Add by Terry 2016-12-08 -> start
	public String getAssignedProgress() {
		return assignedProgress;
	}

	public void setAssignedProgress(String assignedProgress) {
		this.assignedProgress = assignedProgress;
	}
	// Add by Terry 2016-12-08 -> end
}
