package com.fubon.robot.batch.robot.evdata;

import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TSysDepartment generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name="T_SYS_DEPARTMENT")
public class TSysDepartment implements java.io.Serializable {
	// Fields
	/**
	 * 
	 */
	private static final long serialVersionUID = 262688669298030504L;
	@Id
	@Column(name="DEPT_ID")
	private String deptId;
	@Column(name="DEPT_PID")
	private String deptPid;
	@Column(name="DEPT_NO")
	private String deptNo;
	@Column(name="DEPT_NAME")
	private String deptName;
	@Column(name="DEPT_CLS")
	private String deptCls;
	@Column(name="DEPT_DESC")
	private String deptDesc;
	@Column(name="DEPT_STATUS")
	private String deptStatus;
	@Column(name="DEPT_LEVEL")
	private Long deptLevel;
	@Column(name="IS_LAST")
	private boolean isLast;
	@Column(name="MODIFY_TIME")
	private String modifyTime;
	@Column(name="SEE_RIGHT")
	private String seeRight;

	public String getDeptId() {
		return this.deptId;
	}
	
	public String getDeptPid() {
		return deptPid;
	}

	public void setDeptPid(String deptPid) {
		this.deptPid = deptPid;
	}

	public void setLast(boolean isLast) {
		this.isLast = isLast;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptCls() {
		return this.deptCls;
	}

	public void setDeptCls(String deptCls) {
		this.deptCls = deptCls;
	}

	public String getDeptDesc() {
		return this.deptDesc;
	}

	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	public String getDeptStatus() {
		return this.deptStatus;
	}

	public void setDeptStatus(String deptStatus) {
		this.deptStatus = deptStatus;
	}

	public Long getDeptLevel() {
		return this.deptLevel;
	}

	public void setDeptLevel(Long deptLevel) {
		this.deptLevel = deptLevel;
	}


	public boolean getIsLast() {
		return isLast;
	}

	public void setIsLast(boolean isLast) {
		this.isLast = isLast;
	}



	public String getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}


	public String getSeeRight() {
		return seeRight;
	}

	public void setSeeRight(String seeRight) {
		this.seeRight = seeRight;
	}

}
