package com.fubon.robot.batch.robot.evdata;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.log4j.Logger;

/**
 * TTmActivity generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name="T_TM_ACTIVITY")
public class TTmActivity implements java.io.Serializable {
	// Fields
	@Column(name="RESULT_ID")
	private String resultId;// 頁面用字段，通話結果ID
	/**
	 * 
	 */
	private static final long serialVersionUID = 6131570455870040442L;
	
	@Id
	@Column(name="ACTIVITY_ID")
	private String activityId;
	@Column(name="ACTIVITY_CODE")
	private String activityCode;
	@Column(name="ACTIVITY_NAME")
	private String activityName;
	@Column(name="ACTIVITY_DESC")
	private String activityDesc;
	@Column(name="ACTIVITY_STATUS")
	private String activityStatus;
	@Column(name="END_DATE")
	private String endDate;
	@Column(name="START_DATE")
	private String startDate;
	@Column(name="MARKET_TYPE")
	private String marketType;
	@Column(name="MARKET_PRIORITY")
	private String marketPriority;
	@Column(name="MARKET_POLICY")
	private String marketPolicy;
	
	@Column(name="DATA_SOURCE")
	private String dataSource;

	@Column(name="BUSINESS_SOURCE")
	private String businessSource;
	@Column(name="IS_DELETE")
	private String isDelete;
	@Column(name="ACTIVITY_CATALOG")
	private String activityCatalog;
	@Column(name="EMAIL_NOTICE_CONTENT")
	private String emailNoticeContent;
	@Column(name="ORGANIZE_NAME")
	private String organizeName;
	@Column(name ="black_msg_type")
	private String blackMsgType; //add by terry 2018-03-01
	@Column(name ="MSG_CARD")
	private String msgCard;//2018-08-24AddByWillie
	@Column(name ="MSG_CASE")
	private String msgCase;//2018-08-24AddByWillie
	@Column(name ="ACTIVITY_NAME_DEADTIME")
	private Integer activityNameDeadtime;
	@Column(name ="BLACK_NAME_OPEN")
	private String blackNameOpen;// 是否啟用黑名單
	@Column(name ="FILTER_DURATION")
	private Integer filterDuration;// 名單有效日
	
	@Column(name ="VISIT_TYPE")
	private String visitType;// 回訪類型

	public String getMsgCard() {
		return msgCard;
	}

	public void setMsgCard(String msgCard) {
		this.msgCard = msgCard;
	}

	public String getMsgCase() {
		return msgCase;
	}

	public void setMsgCase(String msgCase) {
		this.msgCase = msgCase;
	}

	public String getOrganizeName() {
		return organizeName;
	}

	public void setOrganizeName(String organizeName) {
		this.organizeName = organizeName;
	}


	// Constructors


	public String getVisitType() {
		return visitType;
	}

	public void setVisitType(String visitType) {
		this.visitType = visitType;
	}

	public String getBlackNameOpen() {
		return blackNameOpen;
	}

	public void setBlackNameOpen(String blackNameOpen) {
		this.blackNameOpen = blackNameOpen;
	}

	/** default constructor */
	public TTmActivity() {
	}

	

	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}


	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public String getActivityDesc() {
		return this.activityDesc;
	}

	public void setActivityDesc(String activityDesc) {
		this.activityDesc = activityDesc;
	}

	public String getActivityStatus() {
		return this.activityStatus;
	}

	public void setActivityStatus(String activityStatus) {
		this.activityStatus = activityStatus;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getMarketType() {
		return this.marketType;
	}

	public void setMarketType(String marketType) {
		this.marketType = marketType;
	}

	public String getMarketPriority() {
		return this.marketPriority;
	}

	public void setMarketPriority(String marketPriority) {
		this.marketPriority = marketPriority;
	}

	public String getMarketPolicy() {
		return this.marketPolicy;
	}

	public void setMarketPolicy(String marketPolicy) {
		this.marketPolicy = marketPolicy;
	}

	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public String getBusinessSource() {
		return this.businessSource;
	}

	public void setBusinessSource(String businessSource) {
		this.businessSource = businessSource;
	}

	public Integer getFilterDuration() {
		return filterDuration;
	}

	public void setFilterDuration(Integer filterDuration) {
		this.filterDuration = filterDuration;
	}

	public String getEmailNoticeContent() {
		return this.emailNoticeContent;
	}

	public void setEmailNoticeContent(String emailNoticeContent) {
		this.emailNoticeContent = emailNoticeContent;
	}

	public String getBlackMsgType() {
		return this.blackMsgType;
	}

	public void setBlackMsgType(String blackMsgType) {
		this.blackMsgType = blackMsgType;
	}

	public String getResultId() {
		return resultId;
	}

	public void setResultId(String resultId) {
		this.resultId = resultId;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getActivityCatalog() {
		return activityCatalog;
	}

	public void setActivityCatalog(String activityCatalog) {
		this.activityCatalog = activityCatalog;
	}

	public Integer getActivityNameDeadtime() {
		return activityNameDeadtime;
	}

	public void setActivityNameDeadtime(Integer activityNameDeadtime) {
		this.activityNameDeadtime = activityNameDeadtime;
	}
	
}
