package com.fubon.robot.batch.robot.evdata;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TTmHistoryResult generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name="T_TM_HISTORY_RESULT")
public class TTmHistoryResult implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2870718795825997707L;
	// Fields

	@Id
	@Column(name="call_result_id")
	@GenericGenerator(name = "system-uuid", strategy = "uuid2") 
	@GeneratedValue(generator = "system-uuid")
	private String callResultId;
	@Column(name="RESULT_ID")
	private String resultId;
	@Column(name="CALL_HISTORY_ID")
	private String callHistoryId;
	@Column(name="CUST_ID")
	private String custId;
	@Column(name="ACTIVITY_ID")
	private String activityId;
	@Column(name="CUST_NAME")
	private String custName;
	@Column(name="CSR_ID")
	private String csrId;
	@Column(name="CSR_CODE")
	private String csrCode;
	@Column(name="CSR_NAME")
	private String csrName;
	@Column(name="CSR_WG_ID")
	private String csrWgId;
	@Column(name="CUST_NUMBER")
	private String custNumber; // 撥打客戶電話號碼
	@Column(name="CALLING_TIME")
	private String callingTime; // 通話時間
	@Column(name="IS_DONE")
	private String isDone;
	@Column(name="SUBSCRIPTION_ID")
	private String subscriptionId;
	@Column(name="SUBSCRIPTION_TIME")
	private String subscriptionTime;
	@Column(name="SUBSCRIPTION_NOTE")
	private String subscriptionNote;
	@Column(name="CSR_SUBCODE")
	private String csrSubcode;
	@Column(name="CURR_MONTH")
	private Integer currMonth;
	@Column(name="RESULT_FULLPATH")
	private String resultFullpath;
	@Column(name="SUBSCRIPTION_PHONE")
	private String subscriptionPhone;
	@Column(name="MODIFY_TIME")
	private String modifyTime;
	@Column(name="EXT_FILED1")
	private String extFiled1;
	@Column(name="EXT_FILED2")
	private String extFiled2;// 問卷狀態
	@Column(name="EXT_FILED3")
	private String extFiled3;
	@Column(name="EXT_FILED4")
	private String extFiled4;
	@Column(name="EXT_FILED5")
	private String extFiled5;
	
	private String custdemand;
	@Column(name="ANSWERRECORD_ID")
	private String answerrecordId;
	@Column(name="GEN_DOC_ID")
	private String genDocId;
	@Column(name="VISIT_DOC_ID")
	private String visitDocId;

	@Column(name="COMP_DOC_ID")
	private String compDocId;
//	private boolean isNewCallHisResult;// 是否新新插入通話曆史結果
//	private String softphoneCode; // 話機號碼
	@Column(name="CUSTOMER_STATUS")
	private String customerStatus;
	@Column(name="SERVICE_ITEMS")
	private String serviceItems;
	@Column(name="SERVICEITEMS_ID")
	private String serviceitemsId;
//	private String serviceItemIds;
	@Column(name="IS_CLOSED")
	private String isClosed; // 是否結案
	@Column(name="DELIVERY_STATUS")
	private String deliveryStatus; // 送件狀態 0.已送件 1.已收件 2.退件
	@Column(name="INCLUDED_CONTACT_PERCENTAGE")
	private String includedContactPercentage; // 納入聯絡率
	@Column(name="INCLUDED_SUCCESS_PERCENTAGE")
	private String includedSuccessPercentage; // 納入成功率
	@Column(name="CALLRECORD_ID")
	private String callrecordId; // 通話PID
	@Column(name="RECORDPATH")
	private String recordpath; // 通話錄音檔位置
	@Column(name="RECORD_TIME")
	private String recordTime; // 通話錄音時間

	// add by leo 回訪作業------
//	private String btnType;// 回訪作業三個按鈕類型
	@Column(name="HBCG_COMBO_VALUE")
	private String hbcgComboValue;// 當按鈕為"回訪不成功時",取此值

	// Constructors
	public String getSubscriptionId() {
		return subscriptionId;
	}

	public void setSubscriptionId(String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	public String getSubscriptionTime() {
		return subscriptionTime;
	}

	public void setSubscriptionTime(String subscriptionTime) {
		this.subscriptionTime = subscriptionTime;
	}

	public String getSubscriptionNote() {
		return subscriptionNote;
	}

	public void setSubscriptionNote(String subscriptionNote) {
		this.subscriptionNote = subscriptionNote;
	}

	public String getCsrSubcode() {
		return csrSubcode;
	}

	public void setCsrSubcode(String csrSubcode) {
		this.csrSubcode = csrSubcode;
	}

	public Integer getCurrMonth() {
		return currMonth;
	}

	public void setCurrMonth(Integer currMonth) {
		this.currMonth = currMonth;
	}

	/** default constructor */
	public TTmHistoryResult() {
	}

	/** minimal constructor */
	public TTmHistoryResult(String callHistoryId) {
		this.callHistoryId = callHistoryId;
	}

	// Property accessors

	public String getCallResultId() {
		return this.callResultId;
	}

	public void setCallResultId(String callResultId) {
		this.callResultId = callResultId;
	}


	public String getCallHistoryId() {
		return this.callHistoryId;
	}

	public void setCallHistoryId(String callHistoryId) {
		this.callHistoryId = callHistoryId;
	}

	public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getActivityId() {
		return activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public String getCustName() {
		return custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getCsrId() {
		return csrId;
	}

	public void setCsrId(String csrId) {
		this.csrId = csrId;
	}

	public String getCsrCode() {
		return csrCode;
	}

	public void setCsrCode(String csrCode) {
		this.csrCode = csrCode;
	}

	public String getCsrName() {
		return csrName;
	}

	public void setCsrName(String csrName) {
		this.csrName = csrName;
	}

	public String getCsrWgId() {
		return csrWgId;
	}

	public void setCsrWgId(String csrWgId) {
		this.csrWgId = csrWgId;
	}

	public String getCustNumber() {
		return custNumber;
	}

	public void setCustNumber(String custNumber) {
		this.custNumber = custNumber;
	}

	public String getCallingTime() {
		return callingTime;
	}

	public void setCallingTime(String callingTime) {
		this.callingTime = callingTime;
	}

	public String getIsDone() {
		return isDone;
	}

	public void setIsDone(String isDone) {
		this.isDone = isDone;
	}

	public String getResultId() {
		return resultId;
	}

	public void setResultId(String resultId) {
		this.resultId = resultId;
	}

	
	public String getResultFullpath() {
		return resultFullpath;
	}

	public void setResultFullpath(String resultFullpath) {
		this.resultFullpath = resultFullpath;
	}

	public String getSubscriptionPhone() {
		return subscriptionPhone;
	}

	public void setSubscriptionPhone(String subscriptionPhone) {
		this.subscriptionPhone = subscriptionPhone;
	}

	public String getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getExtFiled1() {
		return extFiled1;
	}

	public void setExtFiled1(String extFiled1) {
		this.extFiled1 = extFiled1;
	}

	public String getExtFiled2() {
		return extFiled2;
	}

	public void setExtFiled2(String extFiled2) {
		this.extFiled2 = extFiled2;
	}

	public String getExtFiled3() {
		return extFiled3;
	}

	public void setExtFiled3(String extFiled3) {
		this.extFiled3 = extFiled3;
	}

	public String getExtFiled4() {
		return extFiled4;
	}

	public void setExtFiled4(String extFiled4) {
		this.extFiled4 = extFiled4;
	}

	public String getExtFiled5() {
		return extFiled5;
	}

	public void setExtFiled5(String extFiled5) {
		this.extFiled5 = extFiled5;
	}

	
	public String getCustdemand() {
		return custdemand;
	}

	public void setCustdemand(String custdemand) {
		this.custdemand = custdemand;
	}

	

//	public String getBtnType() {
//		return btnType;
//	}
//
//	public void setBtnType(String btnType) {
//		this.btnType = btnType;
//	}

	public String getAnswerrecordId() {
		return answerrecordId;
	}

	public void setAnswerrecordId(String answerrecordId) {
		this.answerrecordId = answerrecordId;
	}

	public String getHbcgComboValue() {
		return hbcgComboValue;
	}

	public void setHbcgComboValue(String hbcgComboValue) {
		this.hbcgComboValue = hbcgComboValue;
	}

	public String getGenDocId() {
		return genDocId;
	}

	public void setGenDocId(String genDocId) {
		this.genDocId = genDocId;
	}

	public String getVisitDocId() {
		return visitDocId;
	}

	public void setVisitDocId(String visitDocId) {
		this.visitDocId = visitDocId;
	}

	public String getCompDocId() {
		return compDocId;
	}

	public void setCompDocId(String compDocId) {
		this.compDocId = compDocId;
	}


//	public String getSoftphoneCode() {
//		return softphoneCode;
//	}
//
//	public void setSoftphoneCode(String softphoneCode) {
//		this.softphoneCode = softphoneCode;
//	}

	public String getCustomerStatus() {
		return customerStatus;
	}

	public void setCustomerStatus(String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public String getServiceItems() {
		return serviceItems;
	}

	public void setServiceItems(String serviceItems) {
		this.serviceItems = serviceItems;
	}

	public String getServiceitemsId() {
		return serviceitemsId;
	}

	public void setServiceitemsId(String serviceitemsId) {
		this.serviceitemsId = serviceitemsId;
	}


	public String getIncludedContactPercentage() {
		return includedContactPercentage;
	}

	public void setIncludedContactPercentage(String includedContactPercentage) {
		this.includedContactPercentage = includedContactPercentage;
	}

	public String getIsClosed() {
		return isClosed;
	}

	public void setIsClosed(String isClosed) {
		this.isClosed = isClosed;
	}

	public String getIncludedSuccessPercentage() {
		return includedSuccessPercentage;
	}

	public void setIncludedSuccessPercentage(String includedSuccessPercentage) {
		this.includedSuccessPercentage = includedSuccessPercentage;
	}

	public String getDeliveryStatus() {
		return deliveryStatus;
	}

	public void setDeliveryStatus(String deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	

	
	public String getCallrecordId() {
		return callrecordId;
	}

	public void setCallrecordId(String callrecordId) {
		this.callrecordId = callrecordId;
	}

	public String getRecordpath() {
		return recordpath;
	}

	public void setRecordpath(String recordpath) {
		this.recordpath = recordpath;
	}

	public String getRecordTime() {
		return recordTime;
	}

	public void setRecordTime(String recordTime) {
		this.recordTime = recordTime;
	}

}
