package com.fubon.robot.batch.robot.evdata;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSysUser generated by MyEclipse Persistence Tools
 */

@Entity
@Table(name="t_sys_user")
public class TSysUser implements java.io.Serializable {

	private static final long serialVersionUID = 2283375122132889455L;
	/** 正常 */
	public static String USER_NOMAL_STATUS = "N";
	/** 刪除 */
	public static String USER_DELETE_STATUS = "D";
	/** 掛起 */
	public static String USER_SUSPENSION_STATUS = "S";
	
	@Id
	@Column(name="USER_ID")
	private String userId;
	@Column(name="STYLE_ID")
	private String styleId; // 
	@Column(name="USER_CODE")
	private String userCode;
	@Column(name="USER_CNAME")
	private String userCname;
	@Column(name="USER_EMANE")
	private String userEmane;
	@Column(name="WORK_STATUS")
	private String workStatus;
	
	
	@Column(name="USER_STATUS")
	private String userStatus;
	@Column(name="HOME_TEL")
	private String homeTel;
	@Column(name="SUBCODE")
	private String subcode;
	@Column(name="HOME_ARRESS")
	private String homeArress;
	@Column(name="e_mail")
	private String EMail;

	private String post;
	private String fax;
	private String sex;
	@Column(name="COMP_TEL")
	private String compTel;
	@Column(name="USER_MOBILE")
	private String userMobile;
	private String birthday;
	@Column(name="SOFT_PHONE_LOGIN")
	private String softPhoneLogin;
	@Column(name="SOFT_PHONE_PASS")
	private String softPhonePass;
	@Column(name="USER_TITLE")
	private String userTitle;
	@Column(name="LOGIN_NAME")
	private String loginName;
	@Column(name="LOGIN_PWD")
	private String loginPwd;
	@Column(name="ALLOW_CHANGE_PWD")
	private String allowChangePwd;
	@Column(name="CHANGE_PWD_COUNT")
	private Long changePwdCount;
	
	@Column(name="CALL_IO_TYPE")
	private String callIoType;
	@Column(name="WORK_PATTERN_ID")
	private String workPatternId;
	
	@Column(name="I18N_TYPE")
	private String i18nType;
	@Column(name="LOCATION_CODE")
	private String locationCode;
	@Column(name="MODIFY_TIME")
	private String modifyTime;
	@Column(name="EXT_FILED1")
	private String extFiled1;
	@Column(name="EXT_FILED2")
	private String extFiled2;
	@Column(name="EXT_FILED3")
	private String extFiled3;
	@Column(name="EXT_FILED4")
	private String extFiled4;
	@Column(name="EXT_FILED5")
	private String extFiled5;
	@Column(name="EXT_FILED6")
	private String extFiled6;
	
	@Column(name="START_DATE")
	private String startDate;
	@Column(name="END_DATE")
	private String endDate;
	@Column(name="LOGIN_ERROR_TIME")
	private String loginErrorTime;
	@Column(name="CHANGE_PWD_DAY")
	private String changePwdDay;
	@Column(name="LOCK_STATUS")
	private String lockStatus; // 鎖定狀態
	@Column(name="LAST_MODIFY_USER")
	private String lastModifyUser; // 最後修改人員
	@Column(name="LAST_MODIFY_TIME")
	private String lastModifyTime; // 最後修改時間

	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public String getStyleId() {
		return styleId;
	}
	public void setStyleId(String styleId) {
		this.styleId = styleId;
	}
	public String getUserCode() {
		return userCode;
	}
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	public String getUserCname() {
		return userCname;
	}
	public void setUserCname(String userCname) {
		this.userCname = userCname;
	}
	public String getUserEmane() {
		return userEmane;
	}
	public void setUserEmane(String userEmane) {
		this.userEmane = userEmane;
	}
	public String getWorkStatus() {
		return workStatus;
	}
	public void setWorkStatus(String workStatus) {
		this.workStatus = workStatus;
	}
	public String getUserStatus() {
		return userStatus;
	}
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}
	public String getHomeTel() {
		return homeTel;
	}
	public void setHomeTel(String homeTel) {
		this.homeTel = homeTel;
	}
	public String getSubcode() {
		return subcode;
	}
	public void setSubcode(String subcode) {
		this.subcode = subcode;
	}
	public String getHomeArress() {
		return homeArress;
	}
	public void setHomeArress(String homeArress) {
		this.homeArress = homeArress;
	}
	public String getEMail() {
		return EMail;
	}
	public void setEMail(String eMail) {
		EMail = eMail;
	}
	public String getPost() {
		return post;
	}
	public void setPost(String post) {
		this.post = post;
	}
	public String getFax() {
		return fax;
	}
	public void setFax(String fax) {
		this.fax = fax;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getCompTel() {
		return compTel;
	}
	public void setCompTel(String compTel) {
		this.compTel = compTel;
	}
	public String getUserMobile() {
		return userMobile;
	}
	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}
	public String getBirthday() {
		return birthday;
	}
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	public String getSoftPhoneLogin() {
		return softPhoneLogin;
	}
	public void setSoftPhoneLogin(String softPhoneLogin) {
		this.softPhoneLogin = softPhoneLogin;
	}
	
	public String getSoftPhonePass() {
		return softPhonePass;
	}
	public void setSoftPhonePass(String softPhonePass) {
		this.softPhonePass = softPhonePass;
	}
	public String getUserTitle() {
		return userTitle;
	}
	public void setUserTitle(String userTitle) {
		this.userTitle = userTitle;
	}
	public String getLoginName() {
		return loginName;
	}
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	public String getLoginPwd() {
		return loginPwd;
	}
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}
	public String getAllowChangePwd() {
		return allowChangePwd;
	}
	public void setAllowChangePwd(String allowChangePwd) {
		this.allowChangePwd = allowChangePwd;
	}
	public Long getChangePwdCount() {
		return changePwdCount;
	}
	public void setChangePwdCount(Long changePwdCount) {
		this.changePwdCount = changePwdCount;
	}
	public String getCallIoType() {
		return callIoType;
	}
	public void setCallIoType(String callIoType) {
		this.callIoType = callIoType;
	}
	public String getWorkPatternId() {
		return workPatternId;
	}
	public void setWorkPatternId(String workPatternId) {
		this.workPatternId = workPatternId;
	}
	public String getI18nType() {
		return i18nType;
	}
	public void setI18nType(String i18nType) {
		this.i18nType = i18nType;
	}
	public String getLocationCode() {
		return locationCode;
	}
	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}
	public String getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}
	public String getExtFiled1() {
		return extFiled1;
	}
	public void setExtFiled1(String extFiled1) {
		this.extFiled1 = extFiled1;
	}
	public String getExtFiled2() {
		return extFiled2;
	}
	public void setExtFiled2(String extFiled2) {
		this.extFiled2 = extFiled2;
	}
	public String getExtFiled3() {
		return extFiled3;
	}
	public void setExtFiled3(String extFiled3) {
		this.extFiled3 = extFiled3;
	}
	public String getExtFiled4() {
		return extFiled4;
	}
	public void setExtFiled4(String extFiled4) {
		this.extFiled4 = extFiled4;
	}
	public String getExtFiled5() {
		return extFiled5;
	}
	public void setExtFiled5(String extFiled5) {
		this.extFiled5 = extFiled5;
	}
	public String getExtFiled6() {
		return extFiled6;
	}
	public void setExtFiled6(String extFiled6) {
		this.extFiled6 = extFiled6;
	}
	public String getStartDate() {
		return startDate;
	}
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}
	public String getEndDate() {
		return endDate;
	}
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	public String getLoginErrorTime() {
		return loginErrorTime;
	}
	public void setLoginErrorTime(String loginErrorTime) {
		this.loginErrorTime = loginErrorTime;
	}
	public String getChangePwdDay() {
		return changePwdDay;
	}
	public void setChangePwdDay(String changePwdDay) {
		this.changePwdDay = changePwdDay;
	}
	public String getLockStatus() {
		return lockStatus;
	}
	public void setLockStatus(String lockStatus) {
		this.lockStatus = lockStatus;
	}
	public String getLastModifyUser() {
		return lastModifyUser;
	}
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}
	public String getLastModifyTime() {
		return lastModifyTime;
	}
	public void setLastModifyTime(String lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

}
